# Setup
title:               'Anna Sauer'
tagline:             'ğŸ‹ Stop Making Sense'
description:         '<b>PhD student working on NLP @ IMS Stuttgart</b>'
url:                 https://acidAnn.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Anna Sauer
  url:               ""
  email:             "anna.sauer@ims.uni-stuttgart.de"

# Gems
plugins:
  - jekyll-paginate

# Custom vars
# version:             1.1.0
