# Setup
title:               'acidAnn'
symbol:              'ğŸ‹'
tagline:             'Stop Making Sense'
description:         'A personal page'
url:                 https://acidAnn.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              acidAnn
  url:               ""
  email:             ""

# Gems
plugins:
  - jekyll-paginate
